LOG_PATH: "logs"

LOCAL_DATA_DIR: "data"

LOCAL_EX1_DATA_PATH: "data/ex1/data.zip"
LOCAL_EX1_DATA_FOLDER_DIR: "data/ex1/WikiTableQuestions/csv/200-csv"
LOCAL_EX1_DATA_TABLE_INFO_DIR: "data/ex1/WikiTableQuestions_TableInfo"
LOCAL_EX1_DATA_TABLE_INDEX_DIR: "data/ex1/table_index_dir"

CHINOOK_DBEAVER_DB_PATH: "C:/Users/Hp/AppData/Roaming/DBeaverData/workspace6/.metadata/sample-database-sqlite-1/Chinook.db"
CHINOOK_TABLE_INDEX_DIR: "db/Chinook/sqlite/table_index"

SQLITE_DB_DIR: "db/Chinook/sqlite"
CHROMA_DB_DIR: "db/Chinook/chromadb"

WORKFLOW_VISUALIZATION_DIR: "outputs/Chinook/workflow_visualization"


QUERY_1: "What is the billing city of Leonie Köhler?"
QUERY_1_INITIAL: "LK"
QUERY_2: "Who won best director in the 1972 academy awards?"
QUERY_2_INITIAL: "Best_Dir_1972"


TOP_K: 5
TOP_N: 2
MAX_RETRIES: 3 # attempts to retry failed requests

MODEL_TEMPERATURE: 0.1
MODEL_REQUEST_TIMEOUT: 480 # seconds
MODEL_CONTEXT_WINDOW: 8000
MODEL_OUTPUT_FORMAT: "json"
MODEL_OUTPUT_FORMAT_JSON: true
MODEL_THINKING: true


LOCAL_EMBEDDING_MODEL: "sentence-transformers/all-MiniLM-L6-v2"
LOCAL_LLM_MODEL: "qwen3:0.6b"