LOG_PATH: "logs"

CHINOOK_DB_PATH: "C:/Users/Hp/AppData/Roaming/DBeaverData/workspace6/.metadata/sample-database-sqlite-1/Chinook.db"
CHINOOK_SUMMARIES_DB_PATH: "db/Chinook/sqlite/table_summaries.db"

SQLITE_DB_DIR: "db/Chinook/sqlite"
CHROMA_DB_DIR: "db/Chinook/chromadb"


QUERY_TEXT: "What is the billing city of Leonie Köhler?"
QUERY_TEXT_INITIAL: "LK"


TOP_K: 1
TOP_N: 1
MAX_RETRIES: 3 # attempts to retry failed requests
WORKFLOW_TIMEOUT: 480 # seconds


CHUNK_SIZE: 1000
CHUNK_OVERLAP: 100


MODEL_TEMPERATURE: 0.1
MODEL_REQUEST_TIMEOUT: 480 # seconds
MODEL_CONTEXT_WINDOW: 8000
MODEL_OUTPUT_FORMAT: "json"
MODEL_OUTPUT_FORMAT_JSON: true
MODEL_THINKING: true

FINAL_ANSWER_FORMAT: "answer" # options: "full" or "raw"


LOCAL_EMBEDDING_MODEL: "sentence-transformers/all-MiniLM-L6-v2"
# LOCAL_LLM_MODEL: "qwen3:0.6b"
LOCAL_LLM_MODEL: "gemma3:270m"